//
//  Riasec.swift
//  EduTeam
//
//  Created by Winner Tjandrawan on 22/10/21.
//

import Foundation

var indexArtikel : Int = 0
struct Riasec: Identifiable {
    var id: String
    var nama: String
    var penjelasan: String
    var yangPerluDiketahui: String
    var kelebihanUtama: String
    var pekerjaanKarir: String
    var pelajaran: String

}

var riasecList = [
    Riasec(id: "R",nama: "Realistic_Full", penjelasan: "Orang yang realistis lebih suka bekerja secara manual dan menikmati pengoperasian perangkat atau kendaraan. Banyak profesi realistis melibatkan pekerjaan di luar ruangan, bekerja dengan hewan dan mengharuskan seseorang untuk mengotori tangan mereka. Profesi yang realistis adalah kebalikan dari pekerjaan kantor di mana Anda duduk di dalam sepanjang hari.\n\nHobi umum orang realistis adalah berkebun, memelihara hewan peliharaan, mengotak-atik mobil atau kendaraan lain, dan olahraga luar ruangan seperti bersepeda gunung dan berlari. Sektor yang mencakup banyak profesi realistis termasuk pertanian, konstruksi, manufaktur, distribusi dan transportasi serta perkapalan dan penerbangan.", yangPerluDiketahui: "Tipe R atau Realistic lebih senang beraktivitas atau bekerja terutama dengan tangan, membuat, memperbaiki, merakit atau membangun sesuatu, menggunakan dan mengoperasikan peralatan, perkakas atau mesin. Sering suka bekerja di luar ruangan", kelebihanUtama: "Menggunakan dan mengoperasikan alat, peralatan dan mesin, merancang, membangun, memperbaiki, memelihara, bekerja secara manual, mengukur, bekerja secara detail, mengemudi, memindahkan, merawat hewan, bekerja dengan tanaman", pekerjaanKarir: "Pilot, petani, ahli hortikultura, pembangun, insinyur, personel angkatan bersenjata, montir,tukang kain pelapis, tukang listrik, teknologi komputer, penjaga taman, olahragawan", pelajaran: "- Bahasa Inggris\n- Matematika\n- Sains\n- Workshop\n- Teknologi\n- Komputasi\n- Studi Bisnis\n- Pertanian\n- Hortikultura\n- Pendidikan Jasmani"),
    Riasec(id: "I", nama: "Investigative_Full", penjelasan: "Orang investigasi memiliki rasa ingin tahu, analitis, dan suka belajar. Profesi investigasi mengharuskan seseorang untuk menganalisis tugas-tugas yang ada dengan hati-hati. Banyak profesional investigasi adalah ahli di bidang khusus mereka dan memecahkan masalah melalui penelitian dan analisis.\n\nHobi khas orang investigasi termasuk olahraga intelektual seperti Sudoku dan catur, belajar bahasa yang berbeda atau mengikuti kursus tambahan hanya untuk bersenang-senang. Seseorang akan menemukan banyak profesi investigasi dalam pendidikan akademik, TI, perawatan kesehatan, dan perusahaan inovatif. ", yangPerluDiketahui: "Tipe I atau Investigate suka menemukan dan meneliti ide, mengamati, menyelidiki dan bereksperimen, mengajukan pertanyaan dan memecahkan masalah", kelebihanUtama: "Berpikir analitis dan logis, menghitung, berkomunikasi dengan menulis dan berbicara, merancang, merumuskan, menghitung, mendiagnosis, bereksperimen, menyelidiki", pekerjaanKarir: "Ilmu pengetahuan, penelitian, pekerjaan medis dan kesehatan, ahli kimia, ilmuwan kelautan, teknisi kehutanan, teknisi laboratorium medis atau pertanian, ahli zoologi, dokter gigi, dokter", pelajaran: "- Bahasa Inggris\n- Matematika\n- Sains\n- Komputasi\n- Teknologi"),
    Riasec(id: "A", nama: "Artistic_Full", penjelasan: "Orang-orang artistik pada dasarnya kreatif dan orisinal. Profesi artistik sering kali melibatkan desain dan ekspresi. Profesi artistik atau kreatif mengharuskan seseorang untuk melihat dunia dari perspektif baru yang unik. Ini mungkin melalui gambar dan bahasa, tetapi juga ide-ide itu sendiri.\n\nHobi artistik yang khas termasuk melukis, fotografi, menulis, memasak, kerajinan, desain, dan mengunjungi museum. Seseorang akan menemukan sejumlah besar profesi artistik dalam periklanan, industri musik, teater, sektor seni dan di perusahaan-perusahaan di bidang desain.", yangPerluDiketahui: "Tipe A atau Artistic lebih suka menggunakan kata-kata, seni, musik atau drama untuk berkomunikasi, melakukan, atau mengekspresikan diri, membuat dan merancang sesuatu", kelebihanUtama: "Mengekspresikan secara artistik atau fisik, berbicara, menulis, bernyanyi, melakukan, merancang, mempresentasikan, merencanakan, mengarang, bermain, menari", pekerjaanKarir: "Seniman, ilustrator, fotografer, penulis tanda tangan, komposer, penyanyi, pemain instrumen, penari, aktor, reporter, penulis, editor, pengiklan, penata rambut, perancang busana", pelajaran: "- Bahasa Inggris\n- Ilmu Sosial\n- Musik\n- Drama\n- Seni\n- Desain Grafis\n- Komputasi\n- Studi Bisnis\n- Bahasa"),
    Riasec(id: "S", nama: "Social_Full", penjelasan: "Orang yang mendapat nilai tinggi dalam kategori sosial senang membantu orang lain atau mengajar. Banyak profesi sosial membutuhkan kolaborasi yang intens dengan orang lain atau mempelajari informasi baru bersama-sama. Orang-orang sosial umumnya memiliki preferensi untuk hobi seperti olahraga tim, menjadi sukarelawan, dan makan di luar bersama teman-teman. Banyak profesi sosial dapat ditemukan di pemerintahan, pendidikan, perawatan kesehatan dan pelayanan sosial.", yangPerluDiketahui: "Tipe S atau Social Lebih suka bekerja dengan orang untuk mengajar, melatih dan menginformasikan, membantu, mengobati, menyembuhkan dan menyembuhkan, melayani dan menyapa, peduli terhadap kesejahteraan dan kesejahteraan orang lain", kelebihanUtama: "Berkomunikasi secara lisan atau tertulis, peduli dan mendukung, pelatihan, pertemuan, salam, membantu, mengajar, menginformasikan, wawancara, pembinaan", pekerjaanKarir: "Guru, perawat, asisten perawat, konselor, petugas polisi, pekerja sosial, wiraniaga, petugas layanan pelanggan, pelayan, sekretaris", pelajaran: "- Bahasa Inggris\n- Ilmu Sosial\n- Matematika\n- Sains\n- Kesehatan\n- Pendidikan Jasmani\n- Seni\n- Komputer\n- Studi Bisnis\n- Bahasa"),
    Riasec(id: "E", nama: "Enterprising_Full", penjelasan: "Seperti yang disarankan oleh kata tersebut, orang yang giat suka mengambil inisiatif, bersedia mengambil risiko dan merupakan pemimpin alami. Profesi yang giat sering kali mengharuskan seseorang untuk membuat banyak keputusan (penting), mengarahkan dan membujuk orang, serta bertanggung jawab atas tugas-tugas yang ada.\n\nOrang yang giat akan memiliki preferensi untuk hobi seperti investasi, pelatihan dan pembinaan di klub olahraga, kegiatan sampingan politik dan pekerjaan administrasi lainnya. Profesi wirausaha terutama dapat ditemukan dalam manajemen, pemasaran, perdagangan, administrasi, dan politik. ", yangPerluDiketahui: "Tipe E atau Enterprising suka bertemu orang, memimpin, berbicara dan mempengaruhi orang lain, mendorong orang lain, bekerja dalam bisnis", kelebihanUtama: "Menjual, mempromosikan dan membujuk, mengembangkan ide, berbicara di depan umum, mengelola, mengatur, memimpin dan menjadi kapten, menghitung, merencanakan", pekerjaanKarir: "Penjual, pengacara, politikus, akuntan, pemilik bisnis, eksekutif atau manajer, agen perjalanan, promotor musik, olahraga", pelajaran: "- Bahasa Inggris\n- Matematika\n- Studi Bisnis\n- Akuntansi\n- Ekonomi\n- Ilmu Sosial\n- Drama\n- Komputasi\n- Manajemen Informasi Teks\n- Bahasa"),
    Riasec(id: "C", nama: "Conventional_Full", penjelasan: "Orang konvensional seringkali perfeksionis yang lebih suka bekerja secara terstruktur dan sesuai kesepakatan yang telah ditetapkan. Profesi konvensional seringkali mengharuskan pekerjaan dilakukan sesuai dengan pola atau aturan yang ditetapkan. Selain itu, pekerjaan dapat bersifat rutin atau berbasis proses.\n\nOrang konvensional akan lebih menyukai hobi yang melibatkan pengumpulan barang atau meneliti silsilah keluarga, misalnya. Profesi konvensional sangat umum di dunia perbankan, perusahaan yang terlibat dalam pengelolaan dan pemeliharaan real estat, perusahaan administrasi, sektor keuangan, organisasi pemerintah dan cabang.", yangPerluDiketahui: "Tipe C atau Conventional suka bekerja di dalam ruangan dan pada tugas-tugas yang melibatkan pengorganisasian dan keakuratan, mengikuti prosedur, bekerja dengan data atau angka, merencanakan pekerjaan dan acara", kelebihanUtama: "Menghitung dan mengetik, merekam dan menyimpan catatan, memperhatikan detail, bertemu dan menyapa, melakukan perhitungan, menangani uang, mengatur, mengatur, bekerja secara mandiri", pekerjaanKarir: "Sekretaris, resepsionis, pekerja kantoran, pustakawan, petugas bank, operator komputer, toko dan petugas pengiriman", pelajaran: "- Bahasa Inggris\n- Matematika\n- Studi Bisnis\n- Akuntansi\n- Ekonomi\n- Komputasi\n- Manajemen Informasi Teks")
    
]
